import logging
import os
import platform
import shutil

from datetime import datetime
from logging import Filter
import optuna

from .settings import Settings


logger = logging.getLogger(__name__)

LOG_PATH = "experiment.log"


# =============================================================================
# LOG FILTER
# =============================================================================


class LogFilter(Filter):
    """
    Allow console logs generated by the project code.

    External-library logs are omitted from the console.
    """

    def filter(
        self,
        record: logging.LogRecord,
    ) -> bool:

        return (
            record.name == "__main__"
            or record.name.startswith("src.")
        )


# =============================================================================
# LOG SETUP
# =============================================================================


class LogSetup:
    """
    Configure and manage logging for one experiment run.
    """

    def __init__(
        self,
        settings: Settings,
    ) -> None:

        self.settings = settings

        self.log_level = (
            settings.logging.log_level.upper()
        )

        self.debug_mode = (
            settings.logging.debug
        )

        self.output_dir = (
            settings.data.output_dir
        )

    # =========================================================================
    # SETUP
    # =========================================================================

    def setup_logging(
        self,
    ) -> None:
        """
        Configure file and console logging.
        """

        file_handler = logging.FileHandler(
            LOG_PATH,
            mode="a",
            encoding="utf-8",
        )

        file_handler.setLevel(
            logging.DEBUG
            if self.debug_mode
            else logging.INFO
        )

        console_handler = (
            logging.StreamHandler()
        )

        console_handler.setLevel(
            self.log_level
        )

        console_handler.addFilter(
            LogFilter()
        )

        formatter = logging.Formatter(
            "%(asctime)s | %(levelname)s | %(message)s"
        )

        file_handler.setFormatter(
            formatter
        )

        console_handler.setFormatter(
            formatter
        )

        logging.basicConfig(
            level=(
                logging.DEBUG
                if self.debug_mode
                else logging.INFO
            ),
            handlers=[
                file_handler,
                console_handler,
            ],
            force=True,
        )

        logging.captureWarnings(
            True
        )

        optuna.logging.set_verbosity(
            optuna.logging.WARNING
        )

    # =========================================================================
    # EXPERIMENT METADATA
    # =========================================================================

    def write_log_metadata(
        self,
    ) -> None:
        """
        Write the experiment configuration to the log.
        """

        model_names = ", ".join(
            model.name
            for model in self.settings.model.models
        )

        feature_sets = ", ".join(
            self.settings.model.feature_sets
        )

        aggregations = ", ".join(
            self.settings.model.aggregation_strategies
        )

        reductions = ", ".join(
            self.settings.model.reduction_methods
        )

        pca_indices = ", ".join(
            str(value)
            for value in (
                self.settings.model
                .pca_indices_candidates
            )
        )

        pca_embeddings = ", ".join(
            str(value)
            for value in (
                self.settings.model
                .pca_embeddings_candidates
            )
        )

        metadata = [
            "",
            "========== New Experiment ==========",
            (
                f"Timestamp              : "
                f"{datetime.now().isoformat()}"
            ),
            (
                f"Output directory       : "
                f"{self.output_dir}"
            ),
            (
                f"Platform               : "
                f"{platform.system()} "
                f"{platform.release()}"
            ),
            (
                f"Python version         : "
                f"{platform.python_version()}"
            ),

            "",
            "---------- Data ----------",
            (
                f"Dataset                : "
                f"{self.settings.data.data_path}"
            ),
            (
                f"Schema                 : "
                f"{self.settings.data.schema_path}"
            ),

            "",
            "---------- Pipeline search space ----------",
            (
                f"Feature sets           : "
                f"{feature_sets}"
            ),
            (
                f"Aggregations           : "
                f"{aggregations}"
            ),
            (
                f"Reduction methods      : "
                f"{reductions}"
            ),
            (
                f"PCA indices candidates : "
                f"{pca_indices}"
            ),
            (
                f"PCA embedding candidates: "
                f"{pca_embeddings}"
            ),

            "",
            "---------- Models ----------",
            (
                f"Model families         : "
                f"{model_names}"
            ),
            (
                "Reference baselines    : "
                "mean, median"
            ),
            (
                f"Random state           : "
                f"{self.settings.model.random_state}"
            ),

            "",
            "---------- Nested CV ----------",
            (
                f"Outer folds            : "
                f"{self.settings.validation.outer_splits}"
            ),
            (
                f"Outer repeats          : "
                f"{self.settings.validation.outer_repeats}"
            ),
            (
                f"Inner folds            : "
                f"{self.settings.validation.inner_splits}"
            ),
            (
                f"Optuna trials/family   : "
                f"{self.settings.validation.optuna_trials}"
            ),
            "",
        ]

        with open(
            LOG_PATH,
            "a",
            encoding="utf-8",
        ) as file:

            file.write(
                "\n".join(
                    metadata
                )
            )

    # =========================================================================
    # CLEANUP
    # =========================================================================

    def cleanup(
        self,
    ) -> None:
        """
        Close the experiment log and move it to the run output directory.
        """

        if not os.path.exists(
            LOG_PATH
        ):
            return

        try:

            root_logger = (
                logging.getLogger()
            )

            for handler in (
                root_logger.handlers[:]
            ):

                if isinstance(
                    handler,
                    logging.FileHandler,
                ):
                    handler.close()

                    root_logger.removeHandler(
                        handler
                    )

            shutil.move(
                LOG_PATH,
                os.path.join(
                    self.output_dir,
                    os.path.basename(
                        LOG_PATH
                    ),
                ),
            )

        except Exception as exc:

            logger.warning(
                "Could not move log file "
                "to output directory: %s",
                exc,
            )
