import logging
import os
import platform
import shutil
from datetime import datetime
from logging import Filter

from .settings import Settings


logger = logging.getLogger(__name__)

LOG_PATH = "experiment.log"


# =============================================================================
# LOG FILTER
# =============================================================================


class LogFilter(Filter):
    """
    Allow console messages generated by the project code.

    External library messages are excluded from the console.
    """

    def filter(
        self,
        record: logging.LogRecord,
    ) -> bool:

        logger_name = record.name

        return (
            logger_name == "__main__"
            or logger_name.startswith("src.")
        )


# =============================================================================
# LOG SETUP
# =============================================================================


class LogSetup:
    """
    Configure logging and store experiment metadata.
    """

    def __init__(
        self,
        settings: Settings,
    ) -> None:

        self.settings = settings

        self.log_level = (
            settings.logging.log_level
        )

        self.debug_mode = (
            settings.logging.debug
        )

        self.output_dir = (
            settings.data.output_dir
        )

    def setup_logging(
        self,
    ) -> None:
        """
        Configure file and console logging.
        """

        file_handler = logging.FileHandler(
            LOG_PATH,
            mode="a",
        )

        file_handler.setLevel(
            logging.WARNING
        )

        console_handler = (
            logging.StreamHandler()
        )

        console_handler.setLevel(
            self.log_level.upper()
        )

        console_handler.addFilter(
            LogFilter()
        )

        formatter = logging.Formatter(
            "%(asctime)s | %(levelname)s | %(message)s"
        )

        file_handler.setFormatter(
            formatter
        )

        console_handler.setFormatter(
            formatter
        )

        logging.basicConfig(
            level=(
                logging.DEBUG
                if self.debug_mode
                else logging.INFO
            ),
            handlers=[
                file_handler,
                console_handler,
            ],
            force=True,
        )

        logging.captureWarnings(True)

    # =========================================================================
    # EXPERIMENT METADATA
    # =========================================================================

    def write_log_metadata(
        self,
    ) -> None:
        """
        Write the main experiment configuration to the log file.
        """

        models = ", ".join(
            model.name
            for model in self.settings.model.models
        )

        metadata = [
            "",
            "========== New Experiment ==========",
            f"Timestamp        : {datetime.now().isoformat()}",
            f"Platform         : {platform.system()} {platform.release()}",
            f"Python Version   : {platform.python_version()}",
            "",
            "# Data",
            f"Data Path        : {self.settings.data.data_path}",
            f"Schema Path      : {self.settings.data.schema_path}",
            f"Output Directory : {self.output_dir}",
            "",
            "# Features",
            f"Feature Set      : {self.settings.model.feature_set}",
            f"PCA Components   : {self.settings.model.pca_components}",
            "",
            "# Models",
            f"Models           : {models}",
            f"Random State     : {self.settings.model.random_state}",
            "",
            "# Nested Cross-Validation",
            f"Outer Splits     : {self.settings.validation.outer_splits}",
            f"Inner Splits     : {self.settings.validation.inner_splits}",
            f"Optuna Trials    : {self.settings.validation.optuna_trials}",
            "",
        ]

        with open(
            LOG_PATH,
            "a",
            encoding="utf-8",
        ) as file:

            file.write(
                "\n".join(metadata)
                + "\n"
            )

    # =========================================================================
    # CLEANUP
    # =========================================================================

    def cleanup(
        self,
    ) -> None:
        """
        Close file handlers and move the experiment log
        to the run output directory.
        """

        if not (
            self.output_dir
            and os.path.exists(LOG_PATH)
        ):
            return

        try:
            root_logger = logging.getLogger()

            for handler in (
                root_logger.handlers[:]
            ):
                if isinstance(
                    handler,
                    logging.FileHandler,
                ):
                    handler.close()

                    root_logger.removeHandler(
                        handler
                    )

            shutil.move(
                LOG_PATH,
                os.path.join(
                    self.output_dir,
                    os.path.basename(LOG_PATH),
                ),
            )

        except Exception as exc:
            logger.warning(
                "Could not move log file "
                "to output directory: %s",
                exc,
            )
