import os
import torch
import shutil
import logging
import platform
from logging import Filter
from datetime import datetime

logger = logging.getLogger(__name__)

LOG_PATH = "experiment.log"

class LogFilter(Filter):
    """
    Logging filter that allows all log records generated by user code (loggers named '__main__' or starting with 'src.').
    Log records from external libraries are ignored, regardless of their log level.
    """

    def __init__(self) -> None:
        super().__init__()

    def filter(self, record: logging.LogRecord) -> bool:
        """
        Determines whether a log record should be displayed in the console.

        Parameters
        ----------
        record : logging.LogRecord
            The log record to evaluate.

        Returns
        -------
        bool
            True if the record is from user code and should be logged, False otherwise.
        """
        logger_name = record.name
        return (logger_name == '__main__' or logger_name.startswith('src.'))


class LogSetup:
    """
    Encapsulates logging configuration and management.

    Parameters
    ----------
    log_level : str
        Desired log level for console output (e.g., 'DEBUG', 'INFO', 'WARNING').
    debug_mode : bool
        If True, sets the root logger to DEBUG level; otherwise INFO.
    output_dir : str
        Directory to move the log file to after execution, if specified.
    """

    def __init__(self, log_level: str, debug_mode: bool, output_dir: str):
        self.log_level  = log_level
        self.debug_mode = debug_mode
        self.output_dir = output_dir

    def setup_logging(self) -> None:
        """
        Configure logging with both file and console handlers.
        
        - File handler logs WARNING and above to `LOG_PATH`.
        - Console handler logs at the specified `log_level`.
        - Captures warnings from the `warnings` module.
        """
        file_handler = logging.FileHandler(LOG_PATH, mode="a")
        file_handler.setLevel(logging.WARNING)
 
        console_handler = logging.StreamHandler()
        console_handler.setLevel(self.log_level)
        console_handler.addFilter(LogFilter())

        fmt = "%(asctime)s | %(levelname)s | %(message)s"
        formatter = logging.Formatter(fmt)
        file_handler.setFormatter(formatter)
        console_handler.setFormatter(formatter)

        logging.basicConfig(
            level=logging.DEBUG if self.debug_mode else logging.INFO,
            handlers=[file_handler, console_handler],
            force=True,
        )

        logging.captureWarnings(True)

    def write_log_metadata(self) -> None:
        """
        Write metadata about the experiment run to the log file.
        """
        metadata = [
            "========== New Experiment ==========",
            f"Timestamp       : {datetime.now().isoformat()}",
            f"Output Directory: {self.output_dir}",
            f"Platform        : {platform.system()} {platform.release()}",
            f"Python Version  : {platform.python_version()}",
            f"CUDA Available  : {torch.cuda.is_available()}",
        ]

        env_path = ".env"
        if os.path.exists(env_path):
            metadata.append("\n# .env contents:")
            with open(env_path, "r") as f:
                metadata.extend(["  " + line.strip() for line in f if line.strip()])

        metadata.append("")
        with open(LOG_PATH, "a") as f:
            f.write("\n".join(metadata) + "\n")

    def cleanup(self) -> None:
        """
        Clean up temporary experiment files and, if provided, move the log file
        to the specified output directory.
        """
        shutil.rmtree("catboost_info", ignore_errors=True)

        if self.output_dir and os.path.exists(LOG_PATH):
            try:
                root_logger = logging.getLogger()
                for handler in root_logger.handlers[:]:
                    if isinstance(handler, logging.FileHandler):
                        handler.close()
                        root_logger.removeHandler(handler)

                shutil.move(LOG_PATH, os.path.join(self.output_dir, os.path.basename(LOG_PATH)))
            except Exception as e:
                logger.warning(f"Could not move log file to output directory: {e}")